### ISSUE TITLE
Online Play Network Transport Protocol

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#209]
There are two goals I'd like to reach:

* WASM support.
* Fast.

Currently we are using plain TCP connections for online play, which isn't supported in WASM, and is slow (for lock-step play).

* WebSockets are supported in WASM ([Rust example](https://rustwasm.github.io/wasm-bindgen/examples/websockets.html)), but still backs onto TCP.
* [WebTransport](https://wicg.github.io/web-transport/) is a proposed better method ([slides](https://www.w3.org/2018/12/games-workshop/slides/21-webtransport-webcodecs.pdf), [protocol](https://github.com/WICG/web-transport)), but is still in the works at time of writing.

For speed, ideally we can use UDP at the transport layer, but this isn't able to be used in a browser WASM application (browser security prevents it). Otherwise it would have been nice to use one of the QUIC implementations:

* https://github.com/djc/quinn (more complete)
* https://github.com/mozilla/neqo (Mozilla's)

See:

* [`nes-rust`](https://github.com/takahirox/nes-rust) WebRTC over web sockets.

May be better to use WebRTC over QUIC -- use JS to bridge the gap between the wasm app and QUIC.

**Comment by azriel91** [comment]
It may be possible to use JS to communicate over QUIC, and get the WASM code to talk to JS.

**Comment by Lighty0410** [comment]
Test

**Comment by Lighty0410** [comment]
Test

**Comment by azriel91** [comment]
Closing this issue for initial online play support in the web assembly target. We can investigate faster implementations / protocols at a later date.
